### ISSUE TITLE
Dude!

### ISSUE THREAD

**Issue by ghost** [asif-it/nit-project-report#1]
_You_ are using the Pi. Thought I might need it. Now need to get it myself.

**Comment by asif-ir** [comment]
Hmm. I'm sure you'll find a way. Plus the cost had decreased by about 1k since I got one.

**Comment by ghost** [comment]
And rightfully so.

Anyways, I don't see you around much. Where are you?

**Comment by asif-ir** [comment]
Haha. Parsun awunga college inshallah.
